Add support for nullable min/max
cznic/mathutil pull request #10
Opened 2018-04-25 18:57 UTC by faizandfurious

Adds functions for min/max with pointers, allowing for nullable values.

2018-04-26 08:41 UTC, cznic requested changes
Thanks for the PR. Please address the inline comments, thank you.

2018-04-26 08:41 UTC, cznic commented on mathutil.go
> +	return &r
Can be made allocation free
```go
if *a > *b {
        return a
}

return b
```

2018-04-26 08:41 UTC, cznic commented on mathutil.go
> +	return &r
Can be made allocation free

2018-04-26 08:41 UTC, cznic commented on mathutil.go
> +	return &r
Can be made allocation free

2018-04-26 08:41 UTC, cznic commented on mathutil.go
> +	return &r
Can be made allocation free

2018-04-26 08:41 UTC, cznic commented on mathutil.go
> +	return &r
Can be made allocation free

2018-04-26 08:41 UTC, cznic commented on mathutil.go
> +	return &r
Can be made allocation free

2018-04-26 08:41 UTC, cznic commented on mathutil.go
> +	return &r
Can be made allocation free

2018-04-26 08:41 UTC, cznic commented on mathutil.go
> +	return &r
Can be made allocation free

2018-04-26 08:41 UTC, cznic commented on mathutil.go
> +	return &r
Can be made allocation free

2018-04-26 08:41 UTC, cznic commented on mathutil.go
> +	return &r
Can be made allocation free

2018-04-26 08:41 UTC, cznic commented on mathutil.go
> +	return &r
Can be made allocation free

2018-04-26 08:41 UTC, cznic commented on mathutil.go
> +	return &r
Can be made allocation free

2018-04-26 08:41 UTC, cznic commented on mathutil.go
> +	return &r
Can be made allocation free

2018-04-26 08:41 UTC, cznic commented on mathutil.go
> +	r := MaxInt32(*a, *b)
Can be made allocation free

2018-04-26 08:41 UTC, cznic commented on mathutil.go
> +	return &r
Can be made allocation free

2018-04-26 08:41 UTC, cznic commented on mathutil.go
> +	return &r
Can be made allocation free

2018-04-26 08:41 UTC, cznic commented on mathutil.go
> +	return &r
Can be made allocation free

2018-04-26 08:41 UTC, cznic commented on mathutil.go
> +	return &r
Can be made allocation free

2018-04-26 08:41 UTC, cznic commented on mathutil.go
> +	return &r
Can be made allocation free

2018-04-26 08:41 UTC, cznic commented on mathutil.go
> +	return &r
Can be made allocation free

2018-04-26 16:31 UTC, faizandfurious commented
Changes have been pushed.

2018-04-26 18:09 UTC, bojdell commented
Exciting - thanks for contributing @faizandfurious! This looks good to me, I'll let @cznic have the final approval though

2018-04-28 09:05 UTC, cznic approved these changes
LGTM. Please commit to the master branch, thank you.

2018-04-30 20:54 UTC, cznic commented
I believe it was grantad to you before the LGTM. Let me know if not, I'll send the collaborator's invite again (tomorrow). Maybe it fell into the spam folder?

2018-04-30 21:53 UTC, faizandfurious commented
👍

2018-04-30 21:53 UTC, merged